### ISSUE TITLE
Max retries exceeded with url: /api/auth

### ISSUE THREAD

**Issue by felbinger** [felbinger/PythonFlaskLogin#1]
The application isn't working in production mode (using docker), it's working fine using development config (in pycharm).

```
app_1      | [2020-07-04 17:04:07 +0000] [1] [INFO] Starting gunicorn 19.9.0
app_1      | [2020-07-04 17:04:07 +0000] [1] [DEBUG] Arbiter booted
app_1      | [2020-07-04 17:04:07 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
app_1      | [2020-07-04 17:04:07 +0000] [1] [INFO] Using worker: sync
app_1      | /usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
app_1      |   return io.open(fd, *args, **kwargs)
app_1      | [2020-07-04 17:04:07 +0000] [7] [INFO] Booting worker with pid: 7
app_1      | /usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
app_1      |   return io.open(fd, *args, **kwargs)
app_1      | [2020-07-04 17:04:07 +0000] [8] [INFO] Booting worker with pid: 8
app_1      | /usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
app_1      |   return io.open(fd, *args, **kwargs)
app_1      | [2020-07-04 17:04:07 +0000] [9] [INFO] Booting worker with pid: 9
app_1      | /usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
app_1      |   return io.open(fd, *args, **kwargs)
app_1      | [2020-07-04 17:04:07 +0000] [10] [INFO] Booting worker with pid: 10
app_1      | /usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
app_1      |   return io.open(fd, *args, **kwargs)
app_1      | [2020-07-04 17:04:07 +0000] [1] [DEBUG] 4 workers
app_1      | [2020-07-04 17:04:39 +0000] [7] [DEBUG] GET /login
app_1      | [2020-07-04 17:04:39 +0000] [10] [DEBUG] GET /static/css/sb-admin.css
app_1      | [2020-07-04 17:04:39 +0000] [7] [DEBUG] GET /static/js/utils.js
app_1      | [2020-07-04 17:04:39 +0000] [8] [DEBUG] GET /static/js/login.js
app_1      | [2020-07-04 17:04:40 +0000] [8] [DEBUG] GET /favicon.ico
app_1      | [2020-07-04 17:04:42 +0000] [8] [DEBUG] POST /api/auth
app_1      | [2020-07-04 17:04:43 +0000] [8] [DEBUG] POST /login
app_1      | [2020-07-04 17:04:43,024] ERROR in app: Exception on /login [POST]
app_1      | Traceback (most recent call last):
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
app_1      |     conn = connection.create_connection(
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 80, in create_connection
app_1      |     raise err
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 70, in create_connection
app_1      |     sock.connect(sa)
app_1      | ConnectionRefusedError: [Errno 111] Connection refused
app_1      | 
app_1      | During handling of the above exception, another exception occurred:
app_1      | 
app_1      | Traceback (most recent call last):
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
app_1      |     httplib_response = self._make_request(conn, method, url,
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 354, in _make_request
app_1      |     conn.request(method, url, **httplib_request_kw)
app_1      |   File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
app_1      |     self._send_request(method, url, body, headers, encode_chunked)
app_1      |   File "/usr/local/lib/python3.8/http/client.py", line 1276, in _send_request
app_1      |     self.endheaders(body, encode_chunked=encode_chunked)
app_1      |   File "/usr/local/lib/python3.8/http/client.py", line 1225, in endheaders
app_1      |     self._send_output(message_body, encode_chunked=encode_chunked)
app_1      |   File "/usr/local/lib/python3.8/http/client.py", line 1004, in _send_output
app_1      |     self.send(msg)
app_1      |   File "/usr/local/lib/python3.8/http/client.py", line 944, in send
app_1      |     self.connect()
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in connect
app_1      |     conn = self._new_conn()
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 167, in _new_conn
app_1      |     raise NewConnectionError(
app_1      | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd0289da490>: Failed to establish a new connection: [Errno 111] Connection refused
app_1      | 
app_1      | During handling of the above exception, another exception occurred:
app_1      | 
app_1      | Traceback (most recent call last):
app_1      |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
app_1      |     resp = conn.urlopen(
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
app_1      |     retries = retries.increment(method, url, error=e, _pool=self,
app_1      |   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
app_1      |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
app_1      | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0289da490>: Failed to establish a new connection: [Errno 111] Connection refused'))
app_1      | 
app_1      | During handling of the above exception, another exception occurred:
app_1      | 
app_1      | Traceback (most recent call last):
app_1      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
app_1      |     response = self.full_dispatch_request()
app_1      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
app_1      |     rv = self.handle_user_exception(e)
app_1      |   File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
app_1      |     return cors_after_request(app.make_response(f(*args, **kwargs)))
app_1      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
app_1      |     reraise(exc_type, exc_value, tb)
app_1      |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
app_1      |     raise value
app_1      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
app_1      |     rv = self.dispatch_request()
app_1      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
app_1      |     return self.view_functions[rule.endpoint](**req.view_args)
app_1      |   File "/app/app/views/utils.py", line 41, in wrapper
app_1      |     return view_func(*args, **kwargs)
app_1      |   File "/app/app/views/auth.py", line 27, in login
app_1      |     resp = requests.get(
app_1      |   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get
app_1      |     return request('get', url, params=params, **kwargs)
app_1      |   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request
app_1      |     return session.request(method=method, url=url, **kwargs)
app_1      |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
app_1      |     resp = self.send(prep, **send_kwargs)
app_1      |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
app_1      |     r = adapter.send(request, **kwargs)
app_1      |   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
app_1      |     raise ConnectionError(e, request=request)
app_1      | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0289da490>: Failed to establish a new connection: [Errno 111] Connection refused'))
````

**Comment by felbinger** [comment]
Python backend for frontend wasn't able to reach the api on Port 8080, cause it had been exposed to port 80. Fixed by removing backend for frontend.
